### ISSUE TITLE
Did anybody acutally manage to run this on a real Kubernetes instance

### ISSUE THREAD

**Issue by bernardgut** [khorshuheng/appflowy-self-host-resources#13]
Reac prod K8s instance with securitycontext, non-admin DB backend.

I tried to set this up just reading #1. I get 
```
k logs -n appflowy appflowy-gotrue-8b6858858-pzr64     
{"level":"debug","msg":"Set log level to: debug","time":"2025-07-03T09:35:49Z"}
{"level":"info","msg":"Go runtime metrics collection started","time":"2025-07-03T09:35:49Z"}
{"level":"info","msg":"Create schema if not exists: auth","time":"2025-07-03T09:35:49Z"}
{"level":"debug","msg":"Reading migrations from ./migrations","time":"2025-07-03T09:35:49Z"}
{"level":"debug","msg":"before status","time":"2025-07-03T09:35:49Z"}
[POP] 2025/07/03 09:35:49 sql - BEGIN Transaction --- (conn=tx-894831974910413340, tx=894831974910413340)
[POP] 2025/07/03 09:35:49 sql - CREATE TABLE "schema_migrations" (
"version" VARCHAR (14) NOT NULL,
PRIMARY KEY("version")
);
CREATE UNIQUE INDEX "schema_migrations_version_idx" ON "schema_migrations" (version); (conn=tx-894831974910413340, tx=894831974910413340)
[POP] 2025/07/03 09:35:49 sql - ROLLBACK Transaction --- (conn=tx-894831974910413340, tx=894831974910413340)
{"level":"fatal","msg":"could not execute CREATE TABLE \"schema_migrations\" (\n\"version\" VARCHAR (14) NOT NULL,\nPRIMARY KEY(\"version\")\n);\nCREATE UNIQUE INDEX \"schema_migrations_version_idx\" ON \"schema_migrations\" (version);: ERROR: no schema has been selected to create in (SQLSTATE 3F000)\nmigration status\ngithub.com/supabase/auth/cmd.migrate\n\t/go/src/supabase/auth/cmd/migrate_cmd.go:103\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\ngithub.com/spf13/cobra.(*Command).ExecuteContext\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961\nmain.main\n\t/go/src/supabase/auth/main.go:31\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700","time":"2025-07-03T09:35:49Z"}
```
which seems to indicate this chart is not DB agnostic...

Anybody actually managed to deploy this somewhere else than Minikube ? If yes, then what is the procedure.

Cheers.

**Comment by khorshuheng** [comment]
Yes, I did install this on a k8s which I managed myself. Your issue is actually due to the postgres user not having the "usage" permission on the schema, rather than the type of Kubernetes cluster being used. Something like https://dba.stackexchange.com/questions/106057/error-no-schema-has-been-selected-to-create-in

What permissions does your postgres user currently have on the database?

**Comment by bernardgut** [comment]
Which user ? because apparently there are 2 users for this app. 
The appflowy user is OWNEr
The other one I followed #1  :
```
# connect to the appflowydb
\c appflowydb
CREATE USER supabase_auth_admin BYPASSRLS NOINHERIT CREATEROLE LOGIN NOREPLICATION;
# an extra schema which will be used by the supabase_auth_admin to handle authentication separated from the rest of the setup
CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION supabase_auth_admin;
GRANT USAGE ON SCHEMA auth TO appflowy;
GRANT CREATE ON DATABASE appflowydb TO supabase_auth_admin;
GRANT CONNECT ON DATABASE appflowydb TO supabase_auth_admin;
GRANT supabase_auth_admin TO appflowy;
# make supabase_auth_admin use schema auth per default
ALTER USER supabase_auth_admin SET search_path = 'auth';
# password later used in secrets
# for convenience we use the same password for the user appflowy and the user supabase_auth_admin
ALTER USER supabase_auth_admin WITH PASSWORD 'password';
# create pgvector extension for AI stuff
CREATE EXTENSION IF NOT EXISTS vector;
```

which does contain a GRANT USAGE... 

I also added
```
GRANT USAGE ON SCHEMA public TO supabase_auth_admin;
GRANT CREATE ON SCHEMA public TO supabase_auth_admin;
```

For good measure

**Comment by khorshuheng** [comment]
Ah I see, the instructions in issue 1 are probably a little outdated due to some upstream changes.

I will create a more detailed instructions at a later time for the scenario where the user is using an external postgres, but basically:

1. All services should use the same postgres user, so it's no longer one for gotrue and one for Appflowy cloud services. There is no longer a need to create a separate user for gotrue (eg supabase_auth_admin), which is why I removed the Kubernetes job that performed the migration.

2. The tables for Appflowy cloud services will be on the public schema, whereas the tables for gotrue services will be on auth schema. This schema will be created by gotrue service on start up if not exist already, so there is no need to manually created it.

3. The postgres user is expected to have full access on the database.

**Comment by bernardgut** [comment]
Ok. THanks.

Note : If you are using an external postgres you cannot have 3.

**Comment by khorshuheng** [comment]
@bernardgut Just to check - what is the database url value for your gotrue deployment? i.e. what is the value for https://github.com/khorshuheng/appflowy-self-host-resources/blob/8c89db27dbb9beca66e83da9e7e03530236dea99/charts/appflowy/charts/appflowy-gotrue/templates/deployment.yaml#L45

It should look like: https://github.com/khorshuheng/appflowy-self-host-resources/blob/8c89db27dbb9beca66e83da9e7e03530236dea99/charts/appflowy/templates/_helpers.tpl#L58

**Comment by bernardgut** [comment]
It was using the different supabase_auth_admin account for appflowy. But if I set it back to the same account/pass I get to an error that seems to indicate it might not be migrating things in the right place : 

```
POP] 2025/07/03 16:14:23 sql - BEGIN Transaction --- (conn=tx-7978612757624077542, tx=7978612757624077542)
[POP] 2025/07/03 16:14:23 sql - -- previous backfill migration left last_sign_in_at to be null, which broke some projects

do $$
begin
update auth.identities
  set last_sign_in_at = '2022-11-25'
  where
    last_sign_in_at is null and
    created_at = '2022-11-25' and
    updated_at = '2022-11-25' and
    provider = 'email' and
    id = user_id::text;
end $$;
 (conn=tx-7978612757624077542, tx=7978612757624077542)
[POP] 2025/07/03 16:14:23 sql - ROLLBACK Transaction --- (conn=tx-7978612757624077542, tx=7978612757624077542)
{"args":[0.005691391],"component":"pop","level":"info","msg":"%.4f seconds","time":"2025-07-03T16:14:23Z"}
{"level":"fatal","msg":"running db migrations: error executing migrations/20221208132122_backfill_email_last_sign_in_at.up.sql, sql: -- previous backfill migration left last_sign_in_at to be null, which broke some projects\n\ndo $$\nbegin\nupdate auth.identities\n  set last_sign_in_at = '2022-11-25'\n  where\n    last_sign_in_at is null and\n    created_at = '2022-11-25' and\n    updated_at = '2022-11-25' and\n    provider = 'email' and\n    id = user_id::text;\nend $$;\n: ERROR: operator does not exist: uuid = text (SQLSTATE 42883)","time":"2025-07-03T16:14:23Z"}
```

**Comment by bernardgut** [comment]
Ok so after debgging this further, here is where I am :
- Use the vanilla chart. Dont modify anything
- Manually create DB, assign user Appflowy some extra permissions on the auth chart
- Instantiate chart. At this point all pods start, except appflowy-cloud :
```
k logs -n appflowy appflowy-cloud-5f6b9997ff-2zdsp
AppFlowy Cloud with RUST_LOG=info
Error: Failed to initialize application state: Failed to run migrations: while executing migration 20241126175909: error returned from database: type "af_fragment" already exists

Stack backtrace:
   0: anyhow::kind::Adhoc::new
   1: <core::pin::Pin<P> as core::future::future::Future>::poll
   2: appflowy_cloud::main
   3: std::sys::backtrace::__rust_begin_short_backtrace
   4: main
   5: <unknown>
   6: __libc_start_main
   7: _start
```

almost there...

**Comment by khorshuheng** [comment]
"af_fragment type already exists" error can't be fixed by modifying the chart. We will probably have to modify the migration script for Appflowy cloud such that the application won't try to recreate the type of it already exists (eg. Created by prior migration)

**Comment by bernardgut** [comment]
That is correct. Probably the best would be to use a re entrant migration tool like alembic. 

But in the meantime the issue was that I did not cleaned up the DB properly before re-running the chart. I forgot to clean types. I now have, and I have the exact same issue as https://github.com/khorshuheng/appflowy-self-host-resources/issues/11

```
5vl                  
AppFlowy Cloud with RUST_LOG=info
Error: Failed to initialize application state: Failed to run migrations: while executing migration 20241218090459: error returned from database: relation "af_collab_embeddings" does not exist

Stack backtrace:
   0: anyhow::kind::Adhoc::new
   1: <core::pin::Pin<P> as core::future::future::Future>::poll
   2: appflowy_cloud::main
   3: std::sys::backtrace::__rust_begin_short_backtrace
   4: main
   5: <unknown>
   6: __libc_start_main
   7: _start
```

Thing is I enabled pgvector... But only after the chart failed once. I take it that since migrations are not re-entrant I have to nuke the whole DB and start over, this time doing the setup in the right order... Let me try and report back

**Comment by bernardgut** [comment]
All right it works... kinda. I will update the relevant readme with the relevant info for next people to not waste time.

Right now the pods all cale online except appflowy-cloud :
```
k logs -n appflowy appflowy-cloud-5f6b9997ff-bb85p -f   
AppFlowy Cloud with RUST_LOG=info
```

Those are the only logs after 10 mins.
Not sure if it is hanging or if someone forgot to bind to `[::]` instead of `0.0.0.0`.

```
kubelet            Readiness probe failed: Get "http://[fd00:0:a:1000:2::28fc]:8000/metrics": dial tcp [fd00:0:a:1000:2::28fc]:8000: connect: connection refused
```

can you confirm ?

UPDATE:  confirmed. There are 2 issues with this chart when deployed:
- appflowy cloud doesnt bind to [::]. I am pretty sure Rust supports ipV6 in all its libs so this is really some poor config upstream
- Ingresses do not work OOTB: The current ingress config doesnt fit the k8s standard. So it doesnt work with other IngressClasses than ingress-nginx (I assume it currently works for ingress-nginx but I havent tested it). Will investigate this further

**Comment by khorshuheng** [comment]
On the ingress - yes unfortunately it is assuming that you are using either Nginx, or Traefik. I can't think of a way to make it generic yet. Mainly because there's no generic way to do some of the URL path rewrite. Ultimately, this is an upstream issue, there are ways to simplify the deployment such that we don't need that many custom ingress (or at least, less complicated), but it is hard to change it now due to backward compatibility.

On the binding, it's most likely configuration issue (eg. Binding to 0.0.0.0 by default). I remember there is an env variable to change it, but I need to check. Just to check, is it the metric endpoint (8080, or the API endpoint (80) that has the issue?

**Comment by bernardgut** [comment]
The ipv6 part should be fixed by https://github.com/khorshuheng/appflowy-self-host-resources/pull/14/commits/960bb13b1cdbe7b8121d691a493c3a6e66acb276 in https://github.com/khorshuheng/appflowy-self-host-resources/pull/14

now for the ingress part : I think the focus should be on supporting the standard implementation of ingress in the kubernetes API. in particular with the `pathType` behavior. I will investigate this further and might add a fix to the PR

**Comment by bernardgut** [comment]
It works with the current state of #14 without any additional setup. However, it seems that was only half the battle. The login to the admin pod with the gotrue admin username/password do not work. Is there any other undocumented setup required with this chart @khorshuheng  ?

**Comment by khorshuheng** [comment]
One common mistake which the users made, is that they change the gotrue admin password in the .env variable after installation. So the password is still the same as the one before/the default password (password isn't overwritten if the user already exists).

It used to be, the .env variable will overwrite the existing password of the user. But in this case other users start complaining that when they change password via the UI, it got overwritten when the server starts.

**Comment by bernardgut** [comment]
I didn't do any kind of configuration changes beyond what is in the `values.yaml`. 

I am talking clean DB. Clean setup with Helm chart.  Then going to `<HOST>/console` and trying to login. Then getting this :

![Image](https://github.com/user-attachments/assets/627f3e10-5871-4234-b39e-d7f0582ff7e2)

I will try again to nuke everything and deploy from scratch see if something changes. Note that the pods will crash a couple of times before coming online (probably missing Redis during early init? Who knows... But since they are not re-entrant that might be an issue...)

**Comment by bernardgut** [comment]
On top of that you can see that the login actually succeeds (200) and returns the login page in the response body... clearly there is a problem with the default config:

![Image](https://github.com/user-attachments/assets/bd7ce630-45fd-45ed-a6de-89915f4f1000)

SO I guess the original question of this Issue request persists.

**Comment by khorshuheng** [comment]
Are you able to access /gotrue/settings endpoint? Without this, it is not possible to login. And that depends on the ingress. Basically the requests to /gotrue should be redirected to the gotrue service, with the gotrue prefix stripped. 

Also, it appears the page didn't manage to load properly due to the extension.

**Comment by bernardgut** [comment]
I can if I remove the non-standard (kubernetes API) `/gotrue(/|$)(.*)` regex in the ingress path and replace it with `/gotrue/` :

![Image](https://github.com/user-attachments/assets/67ea44f9-b7e9-49da-b5f3-4b166ae57501)

login on the `/console` still gives me the same CORS errors and still redirect to itself though...

**Comment by bernardgut** [comment]
BTW this is the error in the console : 

<img width="1716" height="283" alt="Image" src="https://github.com/user-attachments/assets/caed554e-f3b6-4885-ab16-26b9d59619fb" />

And if I click on the "Click here to login" I get a 405 Method Not Allowed From the embedded nginx.

**Comment by bernardgut** [comment]
@khorshuheng After replacing the non-standard ingress rewrites with Gateway API resources I am now able to access the settings page :
```
{"external":{"anonymous_users":false,"apple":false,"azure":false,"bitbucket":false,"discord":false,"facebook":false,"figma":false,"fly":false,"github":false,"gitlab":false,"google":false,"keycloak":false,"kakao":false,"linkedin":false,"linkedin_oidc":false,"notion":false,"spotify":false,"slack":false,"slack_oidc":false,"workos":false,"twitch":false,"twitter":false,"email":true,"phone":false,"zoom":false},"disable_signup":false,"mailer_autoconfirm":false,"phone_autoconfirm":false,"sms_provider":"","mfa_enabled":false,"saml_enabled":false}
```
which is more or less what I expected since I didnt setup oauth yet.

still cannot login to the admin console with the helm creds though. Same as before

**Comment by bernardgut** [comment]
Ok so I didnt give up in this. I re-wrote the helm chart and everything works. The only way to do what you were trying to do that did not rely explicitly on non-standard ingress annotations was with the kubernetes  APIGateway. Once I am done I will open a PR.

There is still an issue with appflowy-cloud and the sync feature. The clients cannot connect to the websocket. It seems the sync issue is unrelated to Jubernetes. I get this on the clients: 

```
{"msg":"Starting reconnect attempt 1 of 10","time":"08-13 15:41:25","target":"sync_log"}
{"msg":"establishing WebSocket connection to: wss://DOMAIN:443/ws/v2/26276984-2671-4b96-8925-e1a7d53d28ac?clientId=1603784245&deviceId=010b070b0519489ea11a21a63bbd5e91","time":"08-13 15:41:25","target":"sync_log"}
{"msg":"establishing WebSocket failed to 26276984-2671-4b96-8925-e1a7d53d28ac","time":"08-13 15:41:25","target":"sync_log"}
{"msg":"Reconnect attempt 1 failed: code:UserUnAuthorized msg: Unauthorized websocket connection","time":"08-13 15:41:25","target":"sync_log"}
```

Does this ring a bell @khorshuheng  ?

**Comment by khorshuheng** [comment]
Check the proxy log - chances are, the end point to ws/v2 resulted in a
404. If that is the case, that means the server is version is not the
latest one - especially if you use the default app version that comes with
the helm chart. I should update the default version to use a newer one .

**Comment by bernardgut** [comment]
This was the issue. I think everything works. I will cleanup and push the changes to my fork and submit a PR later.

Thanks for the help
